#!/bin/bash

# Download video from twitter posts
# Saves them as an ogg file named "Username [postId].mp4"
# Copy from the address bar to store the username, otherwise it will be "i"
# Requires ../cookies.txt

url="$1"

# Use a while loop to extract the <username> and <post id> from the URL
IFS='/' read -r _ a b c d e _ <<< "$url"
file="$c [$e]"

# Use yt-dlp to download the audio
yt-dlp --cookies "$(dirname "$0")/../cookies.txt" $url -o "$file"
